---
- set_fact:
    actual_user: "{{ ansible_user }}"

- name: Apt install metasploit deps
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - gpgv2
    - autoconf
    - bison
    - build-essential
    - curl
    - git-core
    - libapr1
    - libaprutil1
    - libcurl4-openssl-dev
    - libgmp3-dev
    - libpcap-dev
    - libpq-dev
    - libreadline6-dev
    - libsqlite3-dev
    - libssl-dev
    - libsvn1
    - libtool
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - locate
    - ncurses-dev
    - openssl
    - postgresql
    - postgresql-contrib
    - wget
    - xsel
    - zlib1g
    - zlib1g-dev

- name: Mkdir msf directory
  become_user: "{{ actual_user }}"
  file:
    state: directory
    path: "/home/vagrant/msf"

- name: Git checkout metasploit source
  become_user: "{{ actual_user }}"
  git:
    repo: https://github.com/rapid7/metasploit-framework.git
    dest: "/home/vagrant/msf"
    update: no

- name: Install necessary gems
  become_user: "{{ actual_user }}"
  gem: name={{ item }} state=latest
  loop:
  - wirble
  - sqlite3
  - bundler

- name: Run bundle install
  become_user: "{{ actual_user }}"
  shell: chdir=/home/vagrant/msf bundle install
