---
- name: Apt install nmap deps
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - git
    - wget
    - build-essential
    - checkinstall
    - libpcre3-dev
    - libssl-dev
    - libpcap-dev

- name: Mkdir $HOME/src/
  file: 
    state: directory
    path: "{{ ansible_env.HOME }}/src/" # usually /root/src/

- name: Git checkout nmap source
  git:
    repo: https://github.com/nmap/nmap.git
    dest: "{{ ansible_env.HOME }}/src/nmap"
    update: no
    #version: 

- name: Run nmap configure
  shell: |
    ./configure
  args:
    chdir: "{{ ansible_env.HOME }}/src/nmap/"
    creates: /usr/local/bin/nmap

- name: Run nmap make
  shell: |
    make
  args:
    chdir: "{{ ansible_env.HOME }}/src/nmap/"
    creates: /usr/local/bin/nmap

- name: Run nmap make install
  shell: |
    make install
  args:
    chdir: "{{ ansible_env.HOME }}/src/nmap/"
    creates: /usr/local/bin/nmap
